application:
  name: testApp
  mode: dev
  port: 7001
  debug: true
logger:
  path: tmp/logs
  level: debug
  type: daily
  maxSize: 64
  maxBackup: 5
  maxAge: 30
  compress: false
database:
  dsn: root:root@tcp(127.0.0.1:3306)/go-hub?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms
  maxOpenConnections: 100
  maxIdleConnections: 25
  maxLifeSeconds: 300
