application:
  name: testApp
  mode: local
  port: 7001
  debug: true
logger:
  path: tmp/logs
  level: debug
  type: daily
  maxSize: 64
  maxBackup: 5
  maxAge: 30
  compress: false
databases:
  - default:
      dsn: root:root@tcp(127.0.0.1:3306)/go-hub?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms
      maxOpenConnections: 100
      maxIdleConnections: 25
      maxLifeSeconds: 300
  - "go-hub-2":
      dsn: root:root@tcp(127.0.0.1:3306)/go-hub-2?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms
      maxOpenConnections: 100
      maxIdleConnections: 25
      maxLifeSeconds: 300
redis:
  host: 127.0.0.1
  port: 6379
  username: ''
  password: ''
  database: 0
