application:
  name: testApp
  mode: dev
  port: 7001
  debug: true
logger:
  path: tmp/logs
  level: debug
  type: daily
  maxSize: 64
  maxBackup: 5
  maxAge: 30
  compress: false
database:
  driver: mysql
  username: root
  password: root
  hostname: 127.0.0.1
  port: 3306
  database: go-hub
  charset: utf8mb4
  maxOpenConnections: 100
  maxIdleConnections: 25
  maxLifeSeconds: 300
